import unittest
from MetaData import MetaData

class MetaDataTest(unittest.TestCase):

    def test_replaceExistingName_twoDuplicatesInMap_AppendNumberThreeToTheName(self):
        meta_data = MetaData()
        meta_data.add_meta_data("Original", "Original")
        meta_data.add_meta_data("Original", "Original1")
        meta_data.add_meta_data("Original", "Original2")
        meta_data.add_meta_data("Original", "Original3")
        self.assertEqual((meta_data.meta_data())["Original_3"], "Original3", "Wrong Name")

    def test_replaceExistingName_noDuplicate_originalNameUsed(self):
        meta_data = MetaData()
        meta_data.add_meta_data("Original", "Original")
        meta_data.add_meta_data("Original", "Original1")
        meta_data.add_meta_data("Original_X", "OriginalX")

        self.assertEqual((meta_data.meta_data())["Original_X"], "OriginalX", "Wrong Name")

    def test_replaceExistingName_useAutoGeneratedName_NameWillBeIncrementedFromBeginning(self):
        meta_data = MetaData()
        meta_data.add_meta_data("Original", "Original")
        meta_data.add_meta_data("Original", "Original")
        meta_data.add_meta_data("Original", "Original")
        meta_data.add_meta_data("Original_2", "Original21")

        self.assertEqual((meta_data.meta_data())["Original_2_1"], "Original21", "Wrong Name")


if __name__ == "__main__":
    unittest.main()